rollback php version update
Deprecated: Creation of dynamic property Drupal\mysql\Driver\Database\mysql\Connection::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Logger\LogMessageParser::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\dblog\Logger\DbLog::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Logger\LoggerChannelFactory::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Session\AccountProxy::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Site\Settings::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\CacheFactory::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\ChainedFastBackendFactory::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\DatabaseCacheTagsChecksum::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\DatabaseBackendFactory::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\ApcuBackendFactory::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\ChainedFastBackend::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Config\CachedStorage::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Config\ExtensionInstallStorage::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\ChainedFastBackend::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Extension\ModuleHandler::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\DependencyInjection\ClassResolver::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property ArrayObject::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Validation\ConstraintManager::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Config\TypedConfigManager::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Language\LanguageDefault::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\language\Config\LanguageConfigFactoryOverride::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Config\ConfigFactory::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\Context\CacheContextsManager::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Cache\Context\CacheContextsManager::$validContextTokens is deprecated in /code/web/core/lib/Drupal/Core/Cache/Context/CacheContextsManager.php on line 265 Deprecated: Creation of dynamic property Drupal\Core\PageCache\ResponsePolicy\KillSwitch::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 Deprecated: Creation of dynamic property Drupal\Core\Messenger\Messenger::$_serviceId is deprecated in /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 288 The website encountered an unexpected error. Please try again later.
RuntimeException: Failed to start the session because headers have already been sent by "/code/web/core/lib/Drupal/Component/DependencyInjection/Container.php" at line 288. in Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() (line 152 of /code/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php).

Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() (Line: 162)
Drupal\Core\Session\SessionManager->startNow() (Line: 110)
Drupal\Core\Session\SessionManager->start() (Line: 57)
Symfony\Component\HttpFoundation\Session\Session->start() (Line: 54)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 709)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)